---
name: Linter

on:  # yamllint disable-line rule:truthy
  workflow_call: # allow this workflow to be called from other workflows

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: codespell-project/actions-codespell@94259cd8be02ad2903ba34a22d9c13de21a74461 # v2.0
        with:
          check_filenames: true

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: pip install yamllint==1.34.0
      - run: yamllint --list-files .

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185 # v3
        with:
          image: ghcr.io/gitleaks/gitleaks:v8.18.1
          options: --volume ${{ github.workspace }}:/work:rw --workdir /work --privileged
          run: gitleaks detect --verbose --source .

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0

  shellcheck:
    runs-on: ubuntu-latest
    container:
      image: docker.io/koalaman/shellcheck-alpine:v0.9.0@sha256:e19ed93c22423970d56568e171b4512c9244fc75dd9114045016b4a0073ac4b7
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: |
          apk add shfmt
          shellcheck --version
          shfmt --version
      - run: |
          [ $(shfmt --list .) ] || exit 0
          shellcheck $(shfmt --list .)

  shfmt:
    runs-on: ubuntu-latest
    container:
      image: docker.io/mvdan/shfmt:v3.7.0-alpine@sha256:fc0a03bb9218218a387adabf09fa22d4a0206d094cf3326a21da34b30ff02ed9
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: |
          shfmt --list .
          shfmt --indent 4 --case-indent --diff .
