---
name: Build

on:  # yamllint disable-line rule:truthy
  workflow_call: # allow this workflow to be called from other workflows

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: paramaxai/nvidia-dind

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Required to checkout
      packages: write # Required to push container image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get branch name
        run: |
          echo "BRANCH=${{ github.head_ref || github.ref_name }}" | tee -a "$GITHUB_ENV"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@dbef88086f6cef02e264edb7dbf63250c17cef6c # v5.5.0
        with:
          images: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.BRANCH }}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
          # actions/delete-package-versions keeps only 1 multi-arch tag if `delete-only-untagged-versions: "true"`
          # remove unknown/unknown architecture from "Package" > "OS/Arch"
          provenance: false
