---
name: Cleaner - container

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  cleaner-container:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete all untagged except latest untagged and main|buildcache
        uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5.0.0
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: container
          min-versions-to-keep: 3
          delete-only-untagged-versions: "true"
          ignore-versions: '(main|buildcache)'
